# Generated by Django 3.2.14 on 2023-02-15 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObmenFolders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя папки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('visible', models.BooleanField(default=True, verbose_name='Показывать папку')),
            ],
        ),
        migrations.CreateModel(
            name='RequestPrinters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('page_utility', models.IntegerField(verbose_name='Страниц отпечатано')),
                ('toner_left', models.IntegerField(verbose_name='Осталось тонера')),
                ('device_name', models.CharField(max_length=200, verbose_name='Сетевое имя')),
                ('changed', models.IntegerField(blank=True, null=True)),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.printersmain', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='GiveDrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.departmentlist', verbose_name='Отдел')),
                ('drum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.drumlist', verbose_name='Модель драма')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Выдано(кем)')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.placeslist', verbose_name='Площадка')),
                ('printermodel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.printermodellist', verbose_name='Модель принтера')),
            ],
        ),
        migrations.CreateModel(
            name='GiveCartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('amount', models.IntegerField(default=1, verbose_name='Количество')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.departmentlist', verbose_name='Отдел')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Выдано(кем)')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.placeslist', verbose_name='Площадка')),
                ('printermodel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.printermodellist', verbose_name='Модель принтера')),
                ('toner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.tonermodellist', verbose_name='Модель картриджа')),
            ],
        ),
    ]
