# Generated by Django 3.2.14 on 2022-07-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_givecartridge_issued_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givecartridge',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
