# Generated by Django 3.2.14 on 2022-07-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_givecartridge_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPrinters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('page_utility', models.CharField(max_length=200)),
                ('toner', models.CharField(max_length=200)),
                ('device_name', models.CharField(max_length=200)),
            ],
        ),
    ]
