# Generated by Django 3.2.14 on 2022-07-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_requestprinters'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestprinters',
            name='toner_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
