# Generated by Django 3.2.14 on 2022-07-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_requestprinters_toner_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestprinters',
            name='changed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
