# Generated by Django 3.2.14 on 2022-07-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_requestprinters_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestprinters',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
