# Generated by Django 3.2.14 on 2022-07-22 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        ('pages', '0007_requestprinters_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestprinters',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.placeslist'),
        ),
    ]
