# Generated by Django 3.2.14 on 2022-07-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_requestprinters_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestprinters',
            old_name='ip',
            new_name='printer',
        ),
        migrations.RenameField(
            model_name='requestprinters',
            old_name='toner',
            new_name='toner_left',
        ),
        migrations.RemoveField(
            model_name='requestprinters',
            name='place',
        ),
    ]
