# Generated by Django 3.2.14 on 2022-07-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20220722_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestprinters',
            name='toner_model',
        ),
        migrations.AlterField(
            model_name='requestprinters',
            name='page_utility',
            field=models.CharField(max_length=200, verbose_name='Страниц отпечатано'),
        ),
    ]
