# Generated by Django 3.2.14 on 2022-07-25 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_dashboard', '0004_auto_20220725_1656'),
        ('pages', '0011_auto_20220725_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givecartridge',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='givecartridge',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.departmentlist', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='givecartridge',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Выдано(кем)'),
        ),
        migrations.AlterField(
            model_name='givecartridge',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.placeslist', verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='givecartridge',
            name='printermodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.printermodellist', verbose_name='Модель принтера'),
        ),
        migrations.AlterField(
            model_name='givecartridge',
            name='toner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.tonermodellist', verbose_name='Модель картриджа'),
        ),
        migrations.AlterField(
            model_name='requestprinters',
            name='device_name',
            field=models.CharField(max_length=200, verbose_name='Сетевое имя'),
        ),
        migrations.AlterField(
            model_name='requestprinters',
            name='toner_left',
            field=models.CharField(max_length=200, verbose_name='Осталось тонера'),
        ),
    ]
