# Generated by Django 3.2.14 on 2022-08-08 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_alter_printersmain_ip'),
        ('pages', '0012_auto_20220725_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='givecartridge',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='requestprinters',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='requestprinters',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.printersmain', verbose_name=''),
        ),
    ]
