# Generated by Django 3.2.14 on 2022-08-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20220808_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestprinters',
            name='page_utility',
            field=models.IntegerField(verbose_name='Страниц отпечатано'),
        ),
    ]
