# Generated by Django 3.2.14 on 2022-08-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_requestprinters_page_utility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestprinters',
            name='toner_left',
            field=models.IntegerField(verbose_name='Осталось тонера'),
        ),
    ]
