# Generated by Django 3.2.14 on 2022-08-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_requestprinters_toner_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='givecartridge',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий'),
        ),
    ]
