# Generated by Django 3.2.14 on 2022-07-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_printersmain_printermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printermodellist',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Модель принтера'),
        ),
        migrations.AlterField(
            model_name='printersmain',
            name='printermodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.printermodellist'),
        ),
    ]
