# Generated by Django 3.2.14 on 2022-07-25 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_auto_20220725_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentlist',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='placeslist',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='printersmain',
            name='comment',
            field=models.CharField(max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='printersmain',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.placeslist', verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='printersmain',
            name='printermodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.printermodellist', verbose_name='Модель принтера'),
        ),
        migrations.AlterField(
            model_name='printersmain',
            name='toner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.tonermodellist', verbose_name='Модель картриджа'),
        ),
        migrations.AlterField(
            model_name='tonermodellist',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Модель картриджа'),
        ),
    ]
