# Generated by Django 3.2.14 on 2022-08-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_auto_20220725_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printersmain',
            name='ip',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='IP'),
        ),
    ]
