# Generated by Django 3.2.14 on 2022-08-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_alter_printersmain_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrumList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Драм')),
            ],
        ),
    ]
